<a href="https://colab.research.google.com/github/Fermu25/Cursos/blob/main/Funciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Funciones**

In [ ]:
from numpy import *
def nombre (var1,var2):
 return array([var1,var2])

In [ ]:
nombre(0,0)

array([0, 0])

In [ ]:
def prom(l):
 n=len(l)
 s=0
 for i in range(n):
  s+=l[i]
 return s/n


In [ ]:
prom ([1,2,3])

2.0

In [ ]:
def punto(l1,l2):
  n1=len(l1)
  n2=len(l2)
  if n1!=n2:
    return 'Vectores con dimension distinta'
  else:
    s=0
    for i in range(n1):
      s+=l1[i]*l2[i]
    return s

In [ ]:
punto([1,1,1],[2,2,2])

6

Arreglos

*   0-int,float
*   1-lista,vector[] ai
*   2-matriz aij
*   3-matrices paralepípedas




In [ ]:
import numpy #from libreria import *lo que queremos / import libreria /se puede poner un alias import numpy as np
v1=numpy.array([1,2,3,4,5])
v2=numpy.array([10,20,30,40,50])
print(v1+v2)


[11 22 33 44 55]


In [ ]:
import numpy as np
v1=np.array([1,2,3,4,5],float) #complex y float me vuelven los elementos complejos o flotantes
v2=np.array([10,20,30,40,50])
#print(v1+v2)
print(v1)
print(v1*v2)

[1. 2. 3. 4. 5.]
[ 10.  40.  90. 160. 250.]


In [ ]:
import numpy as n
a1=n.zeros(3) #zeros nueva funcion, arreglo orden 1 dimension 3
print(a1)
a2=n.zeros([3,3])#arreglo de orden 3, dimension 3
print(a2)
a3=n.ones([5,5],complex) #matriz de 5x5 llena de unos , arreglo de orden 2, dimension 5/ a3=n.ones([5,5,5],complex)
print(a3)
a4=eye(4) #eye regresa la identidad, esta no se puede hacer compleja solo flotante por fuerza
print(a4)


In [ ]:
#Funcion identidad compleja
import numpy as np
def comp(m):#dimension son matrices cuadradas
 Z=np.zeros([m,m],complex)
 for i in range(m):
  for j in range(m):
   if i==j:
    Z[i,i]==1+j
   else:
    Z[i,j]==0
  return Z


In [ ]:
print(comp(3))

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [ ]:
#matriz con complejo conjugado tarea

In [ ]:
import numpy as np
k1=int(input('Da el numero de renglones'))
k2=int(input('Da el numero de columnas'))
A=np.empty([k1,k2],float)#tarea hacerla compleja y hacer la multiplicacion
for i in range(k1):
  for j in range(k2):
    A[i,j]=float(input('Da el elemento (%d,%d)' %(i,j)))
print(A)

In [ ]:
def suma(A1,A2): #Tarea nosotros la multilpicacion
 r1=len(A1) #print(len(A[0])) me da el numero de columnas de la matriz o de elementos de la lista A[0] y print(len(A)) me da el numero de listas que tiene A
 c1=len(A1[0]) #cuanto columnas
 r2=len(A2)
 c2=len(A2[0]) #Supongo que las matrices tienen la misma dimension por eso no me fijo ahorita en r2 y c2
 s=0
 C=np.empty([r1,c1]) #En esta matriz voy a guardar todo
 for i in range(r1):
  for j in range(c1):
    C[i,j]=A1[i,j]+A2[i,j]
 return C


In [ ]:
M1=np.array([[1,2,3],[4,5,6]])
M2=np.array([[10,20,30],[40,50,60]])
print(suma(A1,A2))

[[11. 22. 33.]
 [44. 55. 66.]]


In [ ]:
def sumac(A1,A2): #Tarea nosotros la multilpicacion
 r1=len(A1) #print(len(A[0])) me da el numero de columnas de la matriz o de elementos de la lista A[0] y print(len(A)) me da el numero de listas que tiene A
 c1=len(A1[0]) #cuanto columnas
 r2=len(A2)
 c2=len(A2[0]) #Supongo que las matrices tienen la misma dimension por eso no me fijo ahorita en r2 y c2
 s=0
 C=np.empty([r1,c1]) #En esta matriz voy a guardar todo
 if r1!=r2 or c1!=c2:
  return print('No se pueden sumar')
 else:
  for i in range(r1):
   for j in range(c1):
     C[i,j]=A1[i,j]+A2[i,j]
  return C

In [ ]:
M1=np.eye(4)
M2=np.zeros([4,4])
print(sumac(M1,M2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
def mult(A1,A2): #Multiplicacion de matrices
 r1=len(A1)
 c2=len(A2[0])
 c1=len(A1[0])
 r2=len(A2)
 if c1!=r2:
  return 'No se puede hacer el producto'
 else:
  C=np.empty([r1,c2])
  for i in range(r1):
   for j in range(c2):
    for k in range(c1):
       C[1,j]=+A1[i,k]*A2[k,j]
  return C

In [ ]:
A=ones([100,100],float)
B=ones([100,100],float)
print(mult(A,B))

In [ ]:
#manera de medir el tiempo de computo
#print(np.dot(A,B))
import time
import numpy as np
t0=time.time() #Tiempo inicial
A=ones([100,100],float)
B=ones([100,100],float) #pasos 2N^3 2*100^3
C=zeros([100,100],float)
for i in range(100):
  for j in range(100):
   for k in range(100):
       C[1,j]=+A[i,k]*B[k,j]#tiempo polinomial 2*100*100*100, el 2 es porque se suma y luego se multiplica, dos pasos
print('---tiempo %s'%(time.time()-t0)) #diferencia de tiempos
#Cada vez que haga un algoritmo debo dar el numero de pasos o el tiempo polinomial, p=np

---tiempo 0.6924252510070801


In [ ]:
#Examen 5 marzo
#Tarea leer e investigar sobre el capitulo np, donde np aparece en los simpson y en futurama, problema del vendedor ambulante, el de los basquetbolistas y el cambio de cuerpos