<a href="https://colab.research.google.com/github/Fermu25/Cursos/blob/main/Intro_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. ¿Qué es NumPy?

## Numerical Python <- Biblioteca de Python <- Conjunto de módulos.

Su relevancia está en que proporciona objetos multidimensionales (*numpy arrays*) y funciones matemáticas para operarlos. Es muy útil para procesar datos, manipular matrices, ..., todo lo que vamos a hacer en ciencia de datos.

- **Numpy (*Numerical Python*)**
    - Almacena y opera sobre *buffers**  de datos **densos**
    - **Eficiente** en almacenamiento y operaciones

- **Características**
    - Arrays multidimensionales
    - Slicing e indexado
    - Operaciones matemáticas y lógicas

- **Aplicaciones**
    - Cálculo con vectores y matrices
    - Proporciona objetos fundamentales de Python para algoritmos de ciencia de datos
        - Usado internamente por *scikit-learn* y *SciPy*


**buffer*: espacio de memoria, en el que se almacenan datos de manera temporal, normalmente para un único uso.

# 1. Numpy arrays

- **array** es el *objeto* principal proporcionado por Numpy

- **Características**
    - **Tipo fijo**
        - Todos sus elementos tienen el **mismo tipo**
    - **Multidimensional**
        - Permite representar vectores, matrices y arrays de *n* dimensiones

## 1.1 Numpy arrays vs python lists
En principio, las listas de Python también permiten definir arreglos multidimensionales


- Ventajas de NumPy:

    - Mayor **flexibilidad** en métodos de indexado y operaciones
    - Mayor **eficiencia** en operaciones

    - Dado que las listas pueden contener tipos de datos heterogéneos, almacenan información adicional (**overhead**).

In [ ]:
my_heterog_list = [0.86, 'a', 'b', 4]

<p align="center"><img src="https://drive.google.com/uc?export=view&id=195OL04s0m-ag4agPF0I2QdrGh1TTQP_o" alt="img06.png" width="500"></p>


## 1.2 Mi primer arreglo de NumPy

- Lo primero, siempre, es importar la biblioteca.
- Para transformar objetos en arreglos usamos el método *array*. Documentación en: https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array

In [ ]:
import numpy as np # Una vez llamada la biblioteca numpy, esta no se tiene que llamar nuevamente

#Podemos crear un array a partir de una lista u otro objeto ya existente de tipo array:
lista = [1, 2, 3, 4]
print(type(lista))

arr = np.array(lista)
print(type(arr))

#o pasarle directamente el objeto en el constructor
arr = np.array([1, 2, 3, 4])
print(type(arr))


<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


- **Características de los arrays de Numpy**
    - **Tipo fijo** (*Fixed-type*): sin sobrecarga de memoria
    - **Contiguos** en direcciones de memoria (*Contiguous*): indexación más rápida

- **Tipos de datos en Numpy**
    - Numpy define sus propios tipos de datos
    
    - **Tipos numéricos**
        - `int8`, `int16`, `int32`, `int64`
        - `uint8`, ..., `uint64`
        - `float16`, `float32`, `float64`
    
    - **Valores booleanos**
        - `bool`

In [ ]:
my_numpy_array = np.array([0.67, 0.45, 0.33])

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1IyLuerJVaNEvOtNRWX7AQgJs7gvVcmgS" alt="img07.png" width="500"></p>

## 1.3 <b>Arreglos (arrays) multidimensionales</b>

- Colecciones de elementos organizados a lo largo de un número arbitrario de dimensiones

- Los arreglos multidimensionales pueden representarse con:
    - Listas de Python
    - Arreglos de Numpy

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1HAOI8kTT1IMqdfixY9SL6vUadbXHDDhA" alt="img09.png" width="300"></p>


### Listas de Python

- Arreglos multidimensionales con **listas de Python**

- **Ejemplos:**

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1Il86P9XFSOKafpeE7l8nBLM00kFxYOLZ" alt="img10.png" width="600"></p>



In [ ]:
# Vector (1D array)
list1 = [1, 2, 3]

# Matriz 2D
list2 = [[1, 2, 3],
         [4, 5, 6]]

# Array 3D
list3 = [[[1, 2, 3], [4, 5, 6]],
         [[7, 8, 9], [10, 11, 12]],
         [[13, 14, 15], [16, 17, 18]]]

# Arreglo no homogéneo
list4 = [[1, 2, 3],
         [4, 5],
         [7, 8, 9]]

In [ ]:
#¿Puedo convertir un arreglo no homogéneo en un array?
#arr4 = np.array(list4)

### Arreglos de NumPy
- Arreglos multidimensionales con **Numpy**
    - Se pueden crear directamente a partir de listas de Python
    - **Ejemplos:**

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1X4-besaXCD8odCrtDGI1RQ6T-knXADre" alt="img11.png" width="700"></p>


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([[[1,2,3], [4,5,6]],
                 [[7,8,9], [10,11,12]],
                 [[13,14,15], [16,17,18]]])

- Arreglos multidimensionales con **Numpy**
    - Caracterizados por un conjunto de **ejes** (*axes*) y una **forma** (*shape*)
    - Los **ejes** de un arreglo definen sus dimensiones:
        - Un vector fila (*row vector*) tiene 1 eje (1 dimensión)
        - Una matriz 2D tiene 2 ejes (2 dimensiones)
        - Un arreglo *ND* tiene *N* ejes

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1uAPuEt7a5mrasj77GZJudtWjyfvUVE2F" alt="img12.png" width="600"></p>


- Indexado

    - Los ejes pueden numerarse con valores negativos
    - El eje **-1** siempre corresponde a la fila (*row*)

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1opysAx1g1cNTbXHZkKOn_FfI0rv7sbp2" alt="img13.png" width="600"></p>

In [ ]:
arr_vector = np.array([1, 2, 3])
#Sólo requerimos un índice que nos indice la posición sobre el eje x_0
print(arr_vector[1])

arr_matriz = np.array([[1, 2, 3],
                       [4, 5, 6]])
#Requerimos dos índices en el orden [x_0][x_1].
#Si queremos imprimir el número en la fila 1 columna 2 escribiremos
print(arr_matriz[1][2])

2
6


- Shape
    - La **forma** (*shape*) de un arreglo de Numpy es una tupla que especifica el número de elementos a lo largo de cada eje
    - **Ejemplos:**

  
  <p align="center"><img src="https://drive.google.com/uc?export=view&id=1GH5svWjxpihbX3fScIOcatDn-x7EjeoD" alt="img14.png" width="600"></p>

- **Vector columna vs vector fila**

    - **Ejemplo 1:** Vector columna (matriz 2D)
    
    - **Ejemplo 2:** Vector fila (1D)
    
    - **¡Un vector columna es una matriz 2D!**

  <p align="center"><img src="https://drive.google.com/uc?export=view&id=1HKWVGLvPk0YQy5SF_aBv5SAX48Kt_eoK" alt="img15.png" width="600"></p>


In [ ]:
col_vector = np.array([[0.1], [0.2], [0.3]])
col_vector.shape  # (3, 1)

(3, 1)

In [ ]:
row_vector = np.array([0.1, 0.2, 0.3])
row_vector.shape  # (3,)

(3,)

## 1.4 Creación de arreglos con NumPy

- **Creación desde una lista:**
    - `np.array(my_list, dtype=np.float16)`
        - El tipo de dato se infiere si no se especifica

- **Creación a partir de una forma o un valor:**
    - `np.zeros(shape)`
        - Arreglo con todos los elementos en 0 con la forma dada
    - `np.ones(shape)`
        - Arreglo con todos los elementos en 1 con la forma dada
    - `np.full(shape, value)`
        - Arreglo con todos los elementos con un valor específico y la forma dada

  Documentación y más métodos en: https://numpy.org/doc/stable/reference/routines.array-creation.html

In [ ]:
#Recordatorio: creación de una lista de ceros
my_list = [0] * 10
print(my_list)

my_list2 = [0 for _ in range(10)]
print(my_list2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
# Ejemplos con NumPy
#Crear un arreglo de ceros con forma (2,4)
arr0 = np.zeros((2,4))
print(arr0)
print()

# Crear un arreglo de unos con forma (2,3)
arr1 = np.ones((2,3)) #Como recibe
print(arr1)
print()

# Crear un arreglo lleno de 1.1 con forma (2,1)
arr2 = np.full((2,1), 1.1)
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[1.1]
 [1.1]]


- **Otros métodos útiles:**
    - ``` numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None) ```
      - Devuelve números espaciados uniformemente en un intervalo específico.
      - Ejemplo : `np.linspace(0, 1, 11)`
        - Genera 11 muestras desde 0 hasta 1 (incluido)
        - **Salida:** `[0.0, 0.1, ..., 1.0]`
      
    - `np.arange(1, 7, 2)`
        - Genera números desde 1 hasta 7 (excluido) con paso 2
        - **Salida:** `[1, 3, 5]`
    - `np.random.normal(mean, std, shape)`
        - Genera datos aleatorios con distribución normal
    - `np.random.random(shape)`
        - Genera datos aleatorios distribuidos uniformemente en [0, 1]

In [ ]:
#Comparación entre linespace y arange
arr_ls = np.linspace(0, 10, 101)
print(arr_ls)
print()

arr_ar = np.arange(0, 10, 101)
print(arr_ar)

# ¿Por qué no generan lo mismo? -> ¡ Documentación !

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]

[0]


## 1.5 Atributos principales en un arreglo de NumPy

In [ ]:
# Definir el arreglo
x = np.array([[2, 3, 4, 111], [5, 6, 7, 2222]])

# Número de dimensiones
print(x.ndim)  # Salida: 2

# Forma del arreglo
print(x.shape)  # Salida: (2, 3)

# Tamaño del arreglo (producto de la forma)
print(x.size)  # Salida: 6

2
(2, 4)
8


# 2. <b>Accediendo a Arrays de NumPy</b>

- Los arrays de NumPy pueden accederse de muchas formas:  
    - Indexación simple  
    - Slicing (**segmentación**)  
    - Masking (**enmascaramiento**)  
    - Fancy indexing (**indexación avanzada**)  
    - Combined indexing (**indexación combinada**)  

- El slicing proporciona **vistas** del arreglo considerado:  
    - Las **vistas** permiten **lectura** y **escritura** de datos en el arreglo **original**.  

- El masking y la fancy indexing proporcionan **copias** del arreglo.

Documentación: https://numpy.org/doc/2.3/user/basics.indexing.html

## 2.1 Indexación simple

- Acceso de lectura/escritura a un elemento  
  - `x[i, j, k, ...]`

In [ ]:
# Definir un array de NumPy
x = np.array([[2, 3, 4], [5, 6, 7]])

# Leer un valor del array
el = x[1, 2]  # lectura de valor (indexación)
print("el = %d" % el)

#Nota: [1,2] <- único acceso, más eficiente
print(x[1][2]) # <- dos accesos separados x[1] = [5, 6, 7] y de ahí se escoge el elemento con índice 2

el = 7
7


In [ ]:
# Asignar un nuevo valor
x[1, 2] = 1
print(x)

[[2 3 4]
 [5 6 1]]


- Retorno de elementos desde el final  

    - Consideremos el siguiente array:  
        - `x = np.array([[2, 3, 4], [5, 6, 7]])`  

    - `x[0, -1]`  
        - Obtener el último elemento de la primera fila: `4`  

    - `x[0, -2]`  
        - Obtener el segundo elemento desde el final de la primera fila: `3`  

In [ ]:
# Definir un array de NumPy
x = np.array([[2, 3, 4], [5, 6, 7]])

# Obtener el último elemento de la primera fila
print(x[0, -1])  # Salida esperada: 4

# Obtener el segundo elemento desde el final de la primera fila
print(x[0, -2])  # Salida esperada: 3

4
3


## 2.2 Slicing

- Acceso a elementos contiguos  
    - `x[start:stop:step, ...]`  

    - Crea una **vista** de los elementos desde `start` (incluido) hasta `stop` (excluido), con un paso fijo  
    - **Las modificaciones en la vista afectan el array original**  

    - Atajos útiles:  
        - **Omitir `start`** si quieres empezar desde el inicio del array  
        - **Omitir `stop`** si quieres tomar elementos hasta el final  
        - **Omitir `step`** si no quieres saltar elementos

In [ ]:
# Definir un array de NumPy
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Seleccionar todas las filas y las últimas 2 columnas
print(x[:, 1:])

print(x[:][1:])

[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


- **Seleccionar las dos primeras filas y la primera y tercera columna**  

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1bibAK_166LFtzuniCuIlDKuTJdQRLsXZ" alt="img45-1.png" width="160"></p>

In [ ]:
# Seleccionar las dos primeras filas y la primera y tercera columna
print(x[:2, ::2])

[[1 3]
 [4 6]]


<p align="center"><img src="https://drive.google.com/uc?export=view&id=1s4R4HVwrkTfB1dbN0cd8ncK9yt5B7F3s" alt="img45-2.png" width="160"></p>

- **Actualizar una porción de un array (slicing)**  

In [ ]:
# Definir un array de NumPy
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Asignar 0 a las últimas dos columnas de todas las filas
x[:, 1:] = 0
print(x)

[[1 0 0]
 [4 0 0]
 [7 0 0]]


## 2.3 Otras formas de acceder a arrays

- **Vistas (views)**

In [ ]:
# Definir un array de NumPy
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Crear una vista y modificarla
view = x[:, 1:]
view[:, :] = 0

print(x)  # Salida esperada: [[1, 0, 0], [4, 0, 0], [7, 0, 0]]

[[1 0 0]
 [4 0 0]
 [7 0 0]]


- **Para evitar modificar el array original, usar `.copy()`**  
    - `x1 = x[:,1:].copy()`

- **Masking**: uso de máscaras booleanas para seleccionar elementos  

   - `x[mask]`  
      - `mask`  
         - **boolean**: array de NumPy que especifica qué elementos deben seleccionarse  
         - **same shape**: debe tener la misma forma que el array original  

   - El resultado es un **vector unidimensional** que es una **copia** de los elementos originales seleccionados por la máscara  

- **Creación de máscaras**  

   - `x op valor` (por ejemplo, `x == 4`)  
   - Donde `op` puede ser:  
      - `>` , `>=` , `<` , `<=` , `==` , `!=`  

- **Ejemplos**  

In [ ]:
x = np.array([1.2, 4.1, 1.5, 4.5])
print(x > 4)

[False  True False  True]


In [ ]:
x2 = np.array([[1.2, 4.1], [1.5, 4.5]])
print(x2 >= 4)

[[False  True]
 [False  True]]


- **Operaciones con máscaras (arrays booleanos)**  

   - NumPy permite operaciones booleanas entre máscaras con la misma forma:  
      - `&` (**and**)  
      - `|` (**or**)  
      - `^` (**xor**)  
      - `~` (**negación**)  

   - **Ejemplo**  
      - `mask = ~((x < 1) | (x > 5))`  
      - Selecciona elementos que están entre `1` y `5` (incluidos)  

- **Ejemplos de masking**  

   - Aunque la forma de `x2` sea `(2, 2)`, el resultado es un array **unidimensional** que contiene los elementos que cumplen la condición  

In [ ]:
x = np.array([1.2, 4.1, 1.5, 4.5])
print(x[x > 4])

[4.1 4.5]


In [ ]:
x2 = np.array([[1.2, 4.1], [1.5, 4.5]])
print(x2[x2 >= 4])

[4.1 4.5]


- **Masked array actualizado**

In [ ]:
x = np.array([1.2, 4.1, 1.5, 4.5])
x[x > 4] = 0  # Assignment is allowed
print(x)

[1.2 0.  1.5 0. ]


- **Masking no crea vistas, sino copias**

In [ ]:
x = np.array([1.2, 4.1, 1.5, 4.5])
masked = x[x > 4]  # Masked es una copia de x

masked[:] = 0  # La asignación no afecta a x
print(x)

[1.2 4.1 1.5 4.5]


# 3. Cálculos en NumPy
- **Resumen:**
    - **Funciones universales** (*Ufuncs*):
        - **Operaciones binarias** (`+`, `-`, `*`, ...)
        - **Operaciones unarias** (`exp()`, `abs()`, ...)
    - **Funciones de agregación** (aggregate)
    - **Ordenamiento** (sorting)
    - **Operaciones algebraicas** (producto punto, producto interno)

## 3.1 Funciones universales
- **Funciones universales** (*Ufuncs*): operaciones elemento a elemento
    - **Operaciones binarias** con arreglos de la **misma forma**
        - `+`, `-`, `*`, `/`, `%` (*módulo*), `//` (*división entera*), `**` (*exponenciación*)

Ejemplo:

In [3]:
x = np.array([[1, 1], [2, 2]])
y = np.array([[3, 4], [6, 5]])

result = x * y
print(result)  # Salida: [[3, 4], [12, 10]]

NameError: name 'np' is not defined

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1YcwLwaF4LKh4S4BHcKpeD4KZwaoZbFYu" alt="img22.png" width="500"></p>

- **Funciones universales** (*Ufuncs*):
    - **Operaciones unitarias**
        - `np.abs(x)`
        - `np.exp(x)`, `np.log(x)`, `np.log2(x)`, `np.log10(x)`
        - `np.sin(x)`, `cos(x)`, `tan(x)`, `arctan(x)`, ...
    - Aplican la operación separadamente a cada elemento del arreglo

Ejemplo:

In [ ]:
x = np.array([[1, 1], [2, 2]])
result = np.exp(x)

print(result)  # Salida: [[2.718, 2.718], [7.389, 7.389]]

<p align="center"><img src="https://drive.google.com/uc?export=view&id=14Tt5QsJqxb-uQxnNTRP9uHSbRq19mDR9" alt="img24.png" width="350"></p>

- Nota: El arreglo original no se modifica

## 3.2 Funciones de agregación
(! Muy importantes para preprocesamiento de datos)

 - **Devuelven** un único valor a partir de un arreglo:
      - `np.min(x)`, `np.max(x)`, `np.mean(x)`, `np.std(x)`, `np.sum(x)`
      - `np.argmin(x)`, `np.argmax(x)`
 - Alternativamente, se pueden usar como métodos de un arreglo:
      - `x.min()`, `x.max()`, `x.mean()`, `x.std()`, `x.sum()`
      - `x.argmin()`, `x.argmax()`

**Ejemplos:**


In [ ]:
x = np.array([[1,3],[2,2]])

print(x.min())
print(x.max())
print(x.sum())

- **Funciones de agregación a lo largo de un eje**
    - Permiten especificar el **eje** junto con la operación a realizar

Ejemplos:

In [ ]:
# Se define una matriz 2D con NumPy
x = np.array([[1, 7],
              [2, 4]])

# Encontrar el índice del valor máximo en cada columna (axis=0)
print(x.argmax(axis=0))  # Salida: [1, 0] (índices de los valores máximos en cada columna)

# Sumar los elementos en cada fila (axis=1) o alternativamente axis=-1
#print(x.sum(axis=0))  # Salida: [8, 6] (suma de los elementos en cada fila)

<img src="https://drive.google.com/uc?export=view&id=18FlmEYU82zeGG6tyXOFZwCojcGm3LDsg" alt="img26-1.png" width="200">

<img src="https://drive.google.com/uc?export=view&id=14P4IW0Z8Kw9zuUWm0j-YMfDgLkb0o1FI" alt="img26-2.png" width="130">


## 3.3 Sorting

      


**Ordenamiento**
  - **`np.sort(x)`**: crea una copia ordenada de `x`
      - `x` **no** se modifica
  - **`x.sort()`**: ordena `x` en su lugar (*inplace*)
      - `x` **se modifica**

Por defecto, los arreglos se ordenan a lo largo del último eje (`-1`)

<p align="center"><img src="https://drive.google.com/uc?export=view&id=18936dBxbcXJtmtT9803q9CKJ8cAnLoT6" alt="img29.png" width="390"></p>


In [4]:
# Definir una matriz 2D
x = np.array([[2, 1, 3],
              [7, 9, 8]])

# Ordenar los elementos a lo largo de las filas (axis=-1)
np.sort(x)  # Ordena por filas (axis -1)

NameError: name 'np' is not defined

Se puede especificar el eje para el ordenamiento:

In [ ]:
# Definir una matriz 2D
x = np.array([[2, 7, 3],
              [7, 2, 1]])

# Ordenar los elementos a lo largo de las columnas (axis=0)
np.sort(x, axis=0)  # Ordena por columnas

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1JTeoj-rhZKVNhHapCKZo2zzzxqXqFFSI" alt="img30.png" width="500"></p>

- **Ordenamiento**
    - **`np.argsort(x)`**: devuelve la posición de los índices del arreglo ordenado (por defecto, ordena a lo largo del eje `-1`)

In [ ]:
# Definir una matriz 2D
x = np.array([[1, 1, 1],
              [7, 9, 8]])


<p align="center"><img src="https://drive.google.com/uc?export=view&id=1BJQG9S34HO2RwnwcbVXP9zDsADj-iPVo" alt="img31.png" width="720"></p>


In [ ]:
np.argsort(x)  # Ordena por filas y devuelve los índices

## 3.4 Reshape

Le da una nueva forma (siempre que sea compatible) al arreglo sin modificar los datos.



In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

print(x.reshape((3, 2)))


In [ ]:
print()
print(np.reshape(x, (6,)))  # Salida: [1, 2, 3, 4, 5, 6]
print(x.shape)  #La forma original del array no se modifica

print(x.reshape((5,)))

## 3.5 Operaciones algebraicas

- `np.dot(x, y)`
    - Producto interno si `x` e `y` son arreglos 1D

<p align="center"><img src="https://drive.google.com/uc?export=view&id=14lUh4wHo7sa4CBuWI17Y1R_00wsKELc1" alt="img32.png" width="330"></p>




In [ ]:
# Definir dos vectores 1D
x = np.array([1, 2, 3])
y = np.array([0, 2, 1])  # Funciona incluso si y es un vector fila

# Producto punto entre x e y
np.dot(x, y)  # Salida: 7

- `np.dot(x, y)`
  - Multiplicación de matriz por vector

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1XHsXtd7MzNflAIKtsbkCpbGt240tNc76" alt="img33.png" width="350"></p>


In [ ]:
# Definir una matriz 2D
x = np.array([[1, 1],
              [2, 2]])

# Definir un vector fila
y = np.array([2, 3])  # Funciona incluso si y es un vector fila

# Producto punto entre la matriz x y el vector y
np.dot(x, y)  # Resultado: [5, 10] -> el resultado es un vector fila

- `np.dot(x, y)`
    - Multiplicación de matriz por matriz

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1Dcv5aajkdNK5LGolx_XW9J-3dB-bvgzP" alt="img34.png" width="480"></p>

In [ ]:
# Definir dos matrices 2D con NumPy
x = np.array([[1, 1],
              [2, 2]])

y = np.array([[2, 2],
              [1, 1]])

# Producto punto entre las matrices x e y
np.dot(x, y)  # Resultado: [[3, 3], [6, 6]]


# 4. Extra:

## <b>Trabajando con arreglos</b>

- **Summary**  
   - Array concatenation  
   - Array splitting  
   - Array reshaping  
   - Adding new dimensions

### Concatenación

- Concatenación de arrays a lo largo de un **eje existente**  

  - El resultado tiene el **mismo número de dimensiones** que los arrays de entrada


<p align="center"><img src="https://drive.google.com/uc?export=view&id=1fG0hzsIM1KkVIesfHjWbqVnNyN4wT-m2" alt="img55.png" width="350"></p>


In [1]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[11, 12, 13], [14, 15, 16]])

np.concatenate((x, y), axis=0)  # Eje predeterminado: 0

NameError: name 'np' is not defined

In [ ]:
np.concatenate

- Concatenación a lo largo de **filas** (`axis=1`)

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1rwovM8iL0ZQUkyNckIrJKJFe3SZgD3WN" alt="img56.png" width="400"></p>


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[11, 12, 13], [14, 15, 16]])

np.concatenate((x, y), axis=1)  # Concatenación a lo largo del eje 1

- Concatenación de arrays: **hstack, vstack**
  - Similar a `np.concatenate()`

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1DGStCel8_vMar7yE-out6Tj2p8sP3Kpm" alt="img57.png" width="600"></p>


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[11, 12, 13], [14, 15, 16]])

h = np.hstack((x, y))  # A lo largo de las filas (horizontal)
v = np.vstack((x, y))  # A lo largo de las columnas (vertical)

print(h)

- **vstack** permite concatenar vectores 1-D a lo largo de un **nuevo eje** (no es posible con `np.concatenate`)

<p align="center"><img src="https://drive.google.com/uc?export=view&id=189areG5V_u5ZgzGh4AdNyiJ9uXtN_Agv" alt="img58.png" width="400"></p>


In [ ]:
x = np.array([1, 2, 3])
y = np.array([11, 12, 13])
v = np.vstack((x, y))  # Verticalmente
v

### **Splitting arrays (split, hsplit, vsplit)**

- **np.split()**: regresa una **lista** de arreglos de NumPy

<p align="center"><img src="https://drive.google.com/uc?export=view&id=16XYTZNFJNzOYrEKziUNqkJphkIZqu51t" alt="img59.png" width="450"></p>


In [ ]:
x = np.array([7, 7, 9, 9, 8, 8])
np.split(x, [2, 4])  # separar antes de los elementos 2 y 4

- **hsplit, vsplit** con arreglos 2D  
    - devuelven una **lista** con los arreglos resultantes tras la división

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1ZL8wn_YqxVGywBjFuro1E9Ui5J4K0qVG" alt="img60.png" width="600"></p>


- **En ambos ejemplos la salida es:**
  `Out: [array([[1,2,3],[4,5,6]]), array([[11,12,13],[14,15,16]])]`

### **Cambio de forma de un array**

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1RvZB7IGhd-WELNmMGGMkBhjod4vm5Tqy" alt="img61.png" width="600"></p>


- **La matriz `y` se llena siguiendo el orden de los índices:**
  - `y[0,0] = x[0], y[0,1] = x[1], y[0,2] = x[2]`
  - `y[1,0] = x[3], y[1,1] = x[4], y[1,2] = x[5]`

In [2]:
x = np.arange(6)
y = x.reshape((2, 3))  # cambia la forma de x a una matriz de 2 filas por 3 columnas
y

NameError: name 'np' is not defined

### **Agregando nuevas dimensiones**  
  - `np.newaxis` agrega una nueva dimensión con `shape=1` en la posición especificada

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1mVYWfqBawYJpWbPGL4ianh11ES6L4lsl" alt="img62.png" width="800"></p>


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
res = arr[np.newaxis, :, :]  # salida con forma (1, 2, 3)
print(res)

## Broadcasting (propagación)

- Patrón diseñado para realizar operaciones entre arrays con **diferente forma**.

<p align="center">
    <img src="https://drive.google.com/uc?export=view&id=1b4_bsMhY5uRJpshyqd6ciPL66edJI6qQ" width="500">
</p>


- **Reglas del broadcasting**
    1. La forma del array con **menos dimensiones** se **rellena** con unos iniciales.
        
        ```python
        x.shape = (2, 3), y.shape = (3)  # ⟶ y.shape = (1, 3)
        ```

    2. Si la forma en una dimensión es `1` para uno de los arrays y `>1` para el otro, el array con `shape = 1` en esa dimensión se **expande para coincidir con el otro array**.
        
        ```python
        x.shape = (2, 3), y.shape = (1, 3)  # ⟶ y.shape = (2, 3)  # se expande
        ```

    3. Si existe una dimensión donde ambos arrays tienen `shape > 1`, entonces el broadcasting **no puede realizarse**.

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1o25xrl42dAd4o9GFP4801mJI-HLE1kue" alt="img37.png" width="120"></p>

- **Ejemplo: calcular `x + y`**

In [ ]:
x = np.array([1, 2, 3])
y = np.array([[11], [12], [13]])

z = x + y

print(f"x: {x}","\n")
print(f"y: {y}","\n")
print(f"z: {z}","\n")

- **Aplicar Regla 1**
    - `x.shape` se convierte en `(1, 3)`: `x = [[1, 2, 3]]`

In [ ]:
# Aplicando la Regla 1: agregar una dimensión extra a x
x = np.array([1, 2, 3]).reshape(1, 3)
x


<p align="center"><img src="https://drive.google.com/uc?export=view&id=1Hs7NG_jRz4SZUIzVPWse0oqadGzUcYkH" alt="img38-1.png" width="400"></p>


- **Aplicar Regla 2**:
    - Extender `x` en el eje vertical y `y` en el eje horizontal.
<p align="center"><img src="https://drive.google.com/uc?export=view&id=1mD7yVPmfCntQE7HSWIWektbUzBtwuHgT" alt="img38-2.png" width="600"></p>


- **Ejemplo: calcular `x + y`**

In [ ]:
x = np.array([[1, 2], [3, 4], [5, 6]])  # x.shape = (3, 2)

#x = np.array([1, 2, 3])  # x.shape = (1, 3)
y = np.array([11, 12, 13])  # y.shape = (3,)
z = x + y  # Intento de operación con broadcasting

- **Aplicar Regla 1**:
    - `y.shape` se convierte en `(1, 3)`: `y = [[11, 12, 13]]`
    
- **Aplicar Regla 3**:
    - Las formas `(3, 2)` y `(1, 3)` son incompatibles.
    - NumPy generará una **excepción**.

<p align="center"><img src="https://drive.google.com/uc?export=view&id=1LChaU49nkqeT2cJ3K5kbh6OQ24ihlHp5" alt="img39.png" width="250"></p>

