<a href="https://colab.research.google.com/github/Fermu25/Cursos/blob/main/Practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 1.

## Diccionarios

Escribir un programa que almacene las calificaciones de un semestre en el diccionario {'Electromagnetismo': 10, 'Electrónica': 9, 'Relatividad': 8,'Física Computacional': 10, 'Física Estadística': 9,} y después muestre por pantalla las calificaciones de cada asignatura en el formato *asignatura* como Key y *calificacion* como valor del Key. Al final debe mostrar también el promedio del semestre.


In [ ]:
Calif={'Electromagnetismo': 10, 'Electrónica': 9, 'Relatividad': 8,'Física Computacional': 10, 'Física Estadística': 9}
print(Calif)
n=int(len(Calif))
Ndif=Calif.keys()
s=0
for i in Ndif:
  s+=float(Calif.get(i))
p=s/n
print("El promedio es",p)

{'Electromagnetismo': 10, 'Electrónica': 9, 'Relatividad': 8, 'Física Computacional': 10, 'Física Estadística': 9}
El promedio es 9.2


In [ ]:
peso={} #dicc vacío
peso["H"]=1 #Key H
peso["He"]=2
peso["Cl"]=35.5
print("H":1,"He":2,"Cl":35.5)



## Programa básico de Python

Un satélite se encuentra en una órbita circular alrededor de la Tierra, tal que completa un círculo en $T$ segundos, $T$ es el periodo de la órbita:

i) Muestra que la altitud $h$ sobre la superficie de la Tierra será:
$$
h=\left( \frac{GMT^2}{4\pi^2} \right)^{\tfrac{1}{3}} -R
$$
donde $G$ es la constante de gravitación universal con valor $G=6.67\times10^{-11}$ m$^{3}$kg$^{-1}$s$^{-2}$, $M$ es la masa de la Tierra $M=5.97\times10^{24}$kg y $R$ es el radio de la Tierra $R=6371$ kg.

(ii) Escribe un programa que le pregunte al usuario el periodo que desea tenga su satélite girando alrededor de la Tierra y el programa le regrese la altitud, en metros, que deberá tener.

(iii) ¿Qué altitud deberá tener el satélite su queremos que orbite la Tierra con un periodo de un día (órbita geosíncrona), 90 minutos, 45 minutos? ¿Qué observas?

(iv) En práctica, una órbita geosíncrona es aquella cuya órbita tiene un periodo de un día sideral, que es de 23.93 horas, no de 24 horas. ¿Por qué es esto? ¿Cuál será la diferencia en altitud entre $T$= 23.93 horas y $T$= 24 horas.


Ley de grav.universal
\begin{equation}
F=\frac{GM_{T}m}{(R+h)^2}
\end{equation}
La fuerza de atracción que ejerce la superficie de la tierra sobre un objeto a una distancia R+h en su orbita.
Para un satélite de masa m, la fuerza de atracción de la ley de gravitacion es igual a la fuerza radial sobre el satélite
\begin{equation}
F=ma_{r}
\end{equation}
\begin{equation}
a_{r}=\omega^{2}(R+h)
\end{equation}
\begin{equation}
\omega=\frac{2\pi}{T}
\end{equation}
\begin{equation}
F=\frac{4 \pi^{2}m(R+h)}{T^2}
\end{equation}
Igualando
\begin{equation}
\frac{GM_{T}m}{(R+h)^2}=\frac{4 \pi^{2}m(R+h)}{T^2}
\end{equation}
$$
\frac{GM_{T}T^{2}}{4 \pi^{2}}=(R+h)^3
$$
$$
(R+h)=(\frac{GM_{T}T^{2}}{4 \pi^{2}})^{\frac{1}{3}}
$$
$$
h=\left( \frac{GMT^2}{4\pi^2} \right)^{\tfrac{1}{3}} -R
$$

In [ ]:
import numpy as np
G=6.67*10**(-11) #$G=6.67\times10^{-11}$ m$^{3}$kg$^{-1}$s$^{-2}$
M=5.97e24 #$M$ es la masa de la Tierra $M=5.97\times10^{24}$kg
R=6371 #$R$ es el radio de la Tierra $R=6371$ kg.
def h(T):
  h=((G*M*T**2)/(4*np.pi))**(1/3)-R
  return h

In [ ]:
T=float(input("Cual es el periodo en segundos del satélite \t"))
print("La altitud en metros del satélite es: h=%4.3f" %h(T))

Cual es el periodo en segundos del satélite 	5000
La altitud en metros del satélite es: h=9246505.592


In [ ]:
#¿Qué altitud deberá tener el satélite si queremos que orbite la Tierra con un periodo de un día (órbita geosíncrona), 90 minutos, 45 minutos?
dia=24*60*60
hor1=90*60
hor2=45*60
a=h(dia)
b=h(hor1)
c=h(hor2)
dic={dia:a,hor1:b,hor2:c}
print("Las altitudes son:",dic)
#Como el radio de la tierra es 6371km o 6,371,000 metros, significa que para los periodos de 90mins y 45mins el satélite estaría dentro de la atmósfera terrestre

Las altitudes son: {86400: 61838819.080814995, 5400: 9733636.102196055, 2700: 6129448.987091187}


En práctica, una órbita geosíncrona es aquella cuya órbita tiene un periodo de un día sideral, que es de 23.93 horas, no de 24 horas. ¿Por qué es esto? ¿Cuál será la diferencia en altitud entre  T = 23.93 horas y  T = 24 horas.

In [ ]:
sideral=float(23.93*60*60)
dia=24*60*60
h1=h(sideral)
h2=h(dia)
print("Para la orbita sideral: h1=%4.3f"%h1)
print("Para la orbita sideral: h2=%4.3f"%h2)
print("La diferencia de altitud es:", h2-h1)
#No sé porque es la orbita sideral, pero son 12km de diferencia, supongo que es la diferencia entre dos capas de la atmosfera terrestre, no se la ionosfera y la estratosfera, imagino

Para la orbita sideral: h1=61718506.012
Para la orbita sideral: h2=61838819.081
La diferencia de altitud es: 120313.06924135238


## Matriz de Vandermonde

Considera la matriz de Vandermonde, la cual se define como

$$
A_{ij} = v_i^{j} \;\;\; i=0,1,2, \cdots, n; \;\;\; j=0,1,2,\cdots, n
$$

Crea una función llamada *Vandermonde(v)* que reciba un vector $\vec{v}$ y regrese la matriz A definida arriba.


In [ ]:
import numpy as np
n=int(input('Da el numero de entradas del vector'))
null_list=[]
for i in range(n):
    valor=float(input('Da el elemento %i'%i))
    null_list.append(valor)
v=np.array(null_list,float)
print(v)
def Vandermonde(v):
  A=np.empty([n,n],float)
  for i in range(n):
    for j in range(n):
      A[i,j]=(v[i])**j
  return A
print(Vandermonde(v))

Da el numero de entradas del vector3
Da el elemento 03
Da el elemento 14
Da el elemento 25
[3. 4. 5.]
[[ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


## Matriz tridiagonal

Crea una función llamada tridiagonal que reciba un vector y regrese la matriz cuadrada

$$
A=
\begin{bmatrix}
v_{0} & v_{1}^2 & 0 &  0 & 0 & \dots  & 0 \\
v_{1}^3 & v_{1} & v_{2}^2 &  0 & 0 & \dots  & 0 \\
0 & v_{2}^3 & v_2 &  v_{3}^2 & 0 & \dots  & 0 \\
0 & 0 & v_3^2 &  v_{3} & v_4^2 & \dots  & 0 \\
\dots & \dots  & \dots & \dots & \dots & \dots & \dots\\
0 & 0 & 0 & \dots & v_{n-1}^3 & v_{n-1}  & v_{n}^2 \\
0 & 0 & 0 & 0 & \dots & v_{n}^3  & v_{n} \\
\end{bmatrix}
$$


Prueba con varios vectores e incluye estos vectores en tu código.



In [ ]:
import numpy as np
v=np.array([1,2,3,4,5])
n=len(v)
def tridiagonal(v):
  A=np.empty([n,n],float)
  for i in range(n):
   for j in range(n):
    if i==j:
     A[i,i]=v[i]
    elif i==j-1:
     A[i,j]=v[i+1]**2
    elif i==j+1:
     A[i,j]=v[i]**3
    else:
      A[i,j]=0
  return A
v=np.array([1,2,3,4,5])
print(tridiagonal(v))

[[  1.   4.   0.   0.   0.]
 [  8.   2.   9.   0.   0.]
 [  0.  27.   3.  16.   0.]
 [  0.   0.  64.   4.  25.]
 [  0.   0.   0. 125.   5.]]


## Matriz de Pauli

Las matrices de Pauli son muy populares en Mecánica Cuántica. Se sabe que para una partícula con espín $\tfrac{1}{2}$, como es el electrón, las matrices de Pauli tienen la siguiente forma:

\begin{equation*}
\sigma_x=
\begin{bmatrix}
0&1\\
1&0
\end{bmatrix} \hspace{0.5cm}
\sigma_y=\begin{bmatrix}
0&-i\\
i&0
\end{bmatrix} \hspace{0.5cm}
\sigma_z=\begin{bmatrix}
1&0\\
0&-1
\end{bmatrix}
\end{equation*}

Haz una función llamada *Pauli* que reciba el eje y regrese la matriz de Pauli correspondiente, es decir, escribas *mx=Pauli('x')* y regrese $\sigma_x$.


In [ ]:
import cmath
import numpy as np
def Pauli(eje):
 sigmax=np.array(([0,1],[1,0]))
 sigmay=np.array(([0,-1j],[1j,0]),complex)
 sigmaz=np.array(([1,0],[0,-1]))
 if eje=="x":
  return sigmax
 elif eje=="y":
  return sigmay
 else:
  return sigmaz
eje=input("Qué matriz de Pauli deseas obtener, opciones disponibles 'x','y','z'")
print(Pauli(eje))

Qué matriz de Pauli deseas obtener, opciones disponibles 'x','y','z'x
[[0 1]
 [1 0]]


## Propiedades de las matrices de Pauli

Haremos 3 funciones para comprobar las propiedades más importantes de las matrices de Pauli.

* $\sigma_x^2=\sigma_y^2=\sigma_z^2=\begin{bmatrix}
1&0\\
0&1
\end{bmatrix}$.

Haz una función llamada *matriz\_al\_cuadrado*, que reciba una matriz y regrese su matriz al cuadrado. Ya que tengas tu función, prueba con las 3 matrices de Pauli, generadas en el problema anterior. Hint: Puedes reciclar el código de multiplicación de matrices.

* $Tr(\sigma_i)=0$.

Haz una función llamada traza que reciba una matriz y regrese su traza. Recuerda que la traza de una matriz cuadrada es la suma de los elementos de la diagonal.

* $det(\sigma_i)=-1.$

Haz una función que calcule el determinante de una matriz. Hint: Puedes usar el comando *numpy.linalg.det(M)*, importando *import numpy.linalg* para comprobar el determinante obtenido por tu código.

In [ ]:
def matriz_al_cuadrado(A): #Haz una función llamada matriz_al_cuadrado, que reciba una matriz y regrese su matriz al cuadrado.
 r=len(A)
 c=len(A[0])
 P=np.empty([r,c]) #r=c porque trabajamos con matrices cuadradas  para poder elevar al cuadrado
 for i in range(r):
  for j in range(r):
   s=0
   for k in range(r):
    s+=A[i,k]*A[k,j]
    P[i,j]=s
 return P

In [ ]:
sigmax=np.array(([0,1],[1,0]))
sigmay=np.array(([0,-1j],[1j,0]),complex)
sigmaz=np.array(([1,0],[0,-1]))

print(matriz_al_cuadrado(sigmax))
print(matriz_al_cuadrado(sigmay))
print(matriz_al_cuadrado(sigmaz))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


<ipython-input-123-23661fa3e630>:10: ComplexWarning: Casting complex values to real discards the imaginary part
  P[i,j]=s


In [ ]:
def traza(A): #Haz una función llamada traza que reciba una matriz y regrese su traza
 r=len(A)
 c=len(A[0])
 s=0
 for i in range(r):
  for j in range(r):
    if i==j:
     s+=A[i,j]
 return s


In [ ]:
sigmax=np.array(([0,1],[1,0]))
sigmay=np.array(([0,-1j],[1j,0]),complex)
sigmaz=np.array(([1,0],[0,-1]))
eje=input("Para que matriz de Pauli quieres su traza, elige entre 'x','y' o 'z'")
if eje=="x":
 print("La traza de la matrix de Pauli en el eje %s es: t=%d" %(eje, traza(sigmax)))
elif eje=="y":
 print("La traza de la matrix de Pauli en el eje %s es: t=%d" %(eje, traza(sigmay)))
else:
 print("La traza de la matrix de Pauli en el eje %s es: t=%d" %(eje, traza(sigmaz)))

Para que matriz de Pauli quieres su traza, elige entre 'x','y' o 'z'z
La traza de la matrix de Pauli en el eje z es: t=0


In [ ]:
import numpy as np
def det(A):   #Haz una función que calcule el determinante de una matriz.
 n=len(A)
 if n==1:
  return A[0,0]
 elif n==2:
  return A[0,0]*A[1,1]-A[0,1]*A[1,0]
 else:
  return (A[0,0]*A[1,1]*A[2,2]+A[0,1]*A[1,2]*A[0,2]+A[0,2]*A[1,0]*A[2,1])-(A[2,0]*A[1,1]*A[0,2]+A[2,1]*A[1,2]*A[0,0]+A[2,2]*A[1,0]*A[0,1])
 return det

In [ ]:
import numpy as np
sigmax=np.array(([0,1],[1,0]))
sigmay=np.array(([0,-1j],[1j,0]),complex)
sigmaz=np.array(([1,0],[0,-1]))
det1=np.linalg.det(sigmax)
print(det1)
print(det(sigmax))
M=np.array(([0,1,1],[1,0,1],[1,1,1]))
det2=np.linalg.det(M)
print(det(M))
print(det2)

-1.0
-1
1
1.0


Estaba intenando hacer el determinante para una matriz de n-dimensiones con la regla de Laplace para determinantes, pero no supe como crear las submatrices y por más videos que vi no logré darme idea, entonces mejor hice solo para el caso de una matriz de 3x3 máximo que fue lo que puse en el else del penúltimo código, pero dejo parte de lo que hice por si hay algún tip o ayuda



In [ ]:
#det=0
#  for i in range(n):
#   for j in range (n):
#    Bi=np.empty([n-1,n-1])
#    for k in range(n-1):
#     for l in range(n-1):
#      C[k,l]=A[k+(1 if k>=i else 0), l+(1 if l>=j else 0)]
#      B[i].append(C[k,l])
#    det+=A[i,j]*(-1)**(i+j)*(np.linalg.det(B[i]))